name: publish

on: [push]

jobs:
  publish-status-monitoring:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push to DockerHub
      run: |
        echo $HUB | docker login -u serverboi --password-stdin
        docker build --tag serverboi/status-monitor:amd64-latest .
        docker push serverboi/status-monitor:amd64-latest
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        HUB: ${{ secrets.HUB }}
