name: publish

on: [push]

jobs:
  publish-status-monitoring:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Buildx Docker
      run: |
        echo $HUB | docker login -u serverboi --password-stdin
        docker buildx build \
          --push \
          --platform linux/arm64/v8,linux/amd64 \
          --tag serverboi/status-monitor:latest . 
      env:
        HUB: ${{ secrets.HUB }}
